<?php
/*
 * This file is part of Fields
 *
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Fields\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerField
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerFieldRepository extends EntityRepository
{

}
